# NumPy Notebook

### Motti Bazar

#### Creating NumPy Arrays

In [2]:
# From Python List
import numpy as np

list1 = [1, 2, 3, 4, 5]
arr1 = np.array(list1)
print(arr1)                    # Output: [1 2 3 4 5]

# Create array of 0 and 1
zeros = np.zeros(5)
ones = np.ones((2, 3))
print(zeros)                   # Output: [0. 0. 0. 0. 0.]
print(ones)                    # Output: [[1. 1. 1.]
                               #          [1. 1. 1.]]

[1 2 3 4 5]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [3]:
# Create array with a range of elements
arr = np.arange(0, 10, 2)
print(arr)                     # Output: [0 2 4 6 8]

[0 2 4 6 8]


In [4]:
# Create an array with evenly spaced numbers
arr = np.linspace(0, 1, 5)
print(arr)                     # Output: [0.  0.25  0.5  0.75  1.]

[0.   0.25 0.5  0.75 1.  ]


#### Array Attributes

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)   # Output: 2
print(arr.shape)  # Output: (2, 3)
print(arr.size)   # Output: 6
print(arr.dtype)  # Output: int64

2
(2, 3)
6
int32


#### Array Indexing and Slicing

In [6]:
# Indexing:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])            # Output: 1
print(arr[-1])           # Output: 5

# Slicing:
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])          # Output: [2 3 4]
print(arr[::2])          # Output: [1 3 5]

# Multi-dimensional indexing:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[1, 1])      # Output: 5
print(arr_2d[0:2, 1:3])  # Output: [[2 3]
                         #          [5 6]]

1
5
[2 3 4]
[1 3 5]
5
[[2 3]
 [5 6]]


#### Array Operations

In [7]:
# Element-wise operations
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)  # Output: [5 7 9]
print(arr1 * arr2)  # Output: [4 10 18]
print(arr1 ** 2)    # Output: [1 4 9]

[5 7 9]
[ 4 10 18]
[1 4 9]


#### Broadcasting

In [8]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])
print(arr1 + arr2)
# Output:
# [[11 22 33]
#  [14 25 36]]

[[11 22 33]
 [14 25 36]]


#### Array Reshaping and Flatten

In [9]:
# Reshape
arr = np.arange(12)
reshaped_arr = arr.reshape(3, 4)
print(reshaped_arr)
# Output:
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

# Flatten
flattened_arr = reshaped_arr.flatten()
print(flattened_arr)
# Output: [ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


#### Concatenate and Split

In [10]:
# Concatenate
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate((a, b))
print(c)         # Output: [1 2 3 4 5 6]

# Split
arr = np.arange(9)
split = np.split(arr, 3)
print(split)     # Output: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

[1 2 3 4 5 6]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


#### np.where()

In [12]:
# Basic usage
arr = np.array([1, 2, 3, 4, 5])
result = np.where(arr > 3)
print(result)  # Output: (array([3, 4]),)

# With condition and choices
arr = np.array([1, 2, 3, 4, 5])
result = np.where(arr > 3, arr, -1)
print(result)  # Output: [-1 -1 -1  4  5]

# Multi-dimensional array:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = np.where(arr_2d % 2 == 0, 'even', 'odd')
print(result)
# Output:
# [['odd' 'even' 'odd’]
#  ['even' 'odd' 'even’]
#  ['odd' 'even' 'odd']]

(array([3, 4], dtype=int64),)
[-1 -1 -1  4  5]
[['odd' 'even' 'odd']
 ['even' 'odd' 'even']
 ['odd' 'even' 'odd']]


#### Random Number Generation

In [13]:
# Generate random integers
random_ints = np.random.randint(0, 10, 5)
print(random_ints)     # Output: [3 7 9 1 4] (random result)

# Generate random floats
random_floats = np.random.random(5)
print(random_floats)  # Output: [0.42 0.71 0.18 0.95 0.38] (random result)

[9 4 7 8 0]
[0.79127859 0.40866903 0.10156707 0.2298189  0.62139022]


#### Mathematical/Statistical Functions

In [14]:
# Basic operations
arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))         # Output: 15
print(np.prod(arr))        # Output: 120
print(np.mean(arr))        # Output: 3.0
print(np.std(arr))         # Output: 1.41...
print(np.min(arr))         # Output: 1
print(np.max(arr))         # Output: 5
print(np.median(arr))      # Output: 3.0

# Exponential and logarithmic functions
arr = np.array([1, 2, 3])
print(np.exp(arr))         # Output: [ 2.71828183  7.3890561  20.08553692]
print(np.log(arr))         # Output: [0.         0.69314718 1.09861229]

# Percentiles
arr = np.array([1, 2, 3, 4, 5])
print(np.percentile(arr, 50))               # Output: 3.0 (median)
print(np.percentile(arr, [25, 50, 75]))     # Output: [2. 3. 4.]

15
120
3.0
1.4142135623730951
1
5
3.0
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
3.0
[2. 3. 4.]
